### ISSUE TITLE
Magic for click

### ISSUE THREAD

**Issue by cthoyt** [scolby33/easy_config#4]
Maybe this should go in a different repo, but it would be cool to make a decorator from an easy config class that would install the right options in a cli script and also make the config available either as the ctx.obj or some other way if it’s static

**Comment by scolby33** [comment]
Can you write a notional script of how this would look?

**Comment by cthoyt** [comment]
Here's a quick reference implementation and a couple tests (they pass)

```python

# -*- coding: utf-8 -*-

"""Test the click wrapper."""

import dataclasses
from typing import Type

import click
from click.testing import CliRunner

from easy_config import EasyConfig


def args_from_config(cls: Type[EasyConfig]):
    """Build a decorator based on the given easy config class."""

    def decorate(command):
        """Decorate the :mod:`click` command."""
        for field in dataclasses.fields(cls):
            print(field)
            if field.default is dataclasses.MISSING:
                wrapper = click.argument(field.name, type=field.type)
            else:
                wrapper = click.option(f'--{field.name}', type=field.type, default=field.default)

            command = wrapper(command)

        return command

    return decorate


def test_option():
    """Test that when a default is available, a :func:`click.option` is used."""

    class ExampleConfig(EasyConfig):
        """Example EasyConfig subclass to test with."""

        FILES = None
        NAME = 'MyProgram'

        number: int = 4

    @click.command()
    @args_from_config(ExampleConfig)
    def main(number):
        click.echo(f'number: {number}')

    runner = CliRunner()
    result = runner.invoke(main)
    assert result.output == 'number: 4\n', 'incorrect output'

    result = runner.invoke(main, ['--number', '5'])
    assert result.output == 'number: 5\n'


def test_argument():
    """Test that when a default is not available, a :func:`click.argument` is used."""

    class ExampleConfig(EasyConfig):
        """Example EasyConfig subclass to test with."""

        FILES = None
        NAME = 'MyProgram'

        number: int

    @click.command()
    @args_from_config(ExampleConfig)
    def main(number):
        click.echo(f'number: {number}')

    runner = CliRunner()
    result = runner.invoke(main, ['4'])
    assert result.output == 'number: 4\n'

```

**Comment by cthoyt** [comment]
Not sure if this belongs in this package, or would be better stand-alone, since it introduces the requirement of click

**Comment by scolby33** [comment]
I can see three options, in no particular order:

- `import click` is an extra and `args_from_config` is an instance method (probably with a different name) on `EasyConfig` subclasses
- `import click` is an extra and `args_from_config` is a function in another module (`compat`?)
- the whole thing is an example in a new folder in the root of the repos called `recipes` or something and is documented as a recipe in the (eventual) Sphinx docs

I can see arguments for and against all of these:

- using extras is kinda weird and not all that common, might be confusing
- instance method keeps things close but adds cruft to the class whereas a function elsewhere spreads things out (as I type this I think I like the function elsewhere a bit better)
- the recipes approach keeps the main package clean and focused but makes it harder to implement things for the end user. However, it might be better because the way you've written the decorator makes it a one-trick pony: many people might end up implementing a slightly-different custom version of their own anyway.

What do you think?
