### ISSUE TITLE
Wrong type annotations

### ISSUE THREAD

**Issue by cthoyt** [scolby33/easy_config#6]
`EasyConfig._load_file` takes either a `Path` or a `TextIO`. It seems to work with a string, but this needs to be updated

https://github.com/scolby33/easy_config/blob/f7801583ba7a393188b2d90a66046892b9cb2345/tests/test_easy_config.py#L34

**Comment by scolby33** [comment]
What do you mean about line 34 of the tests?

**Comment by cthoyt** [comment]
str isn't a valid type to pass to _load_file. Check the PR

**Comment by scolby33** [comment]
Oh I thought you meant that line needed to be changed.

I sorta did this on purpose. People should pass in Paths. It turns out strs and Paths are identical as far as `open` is concerned. Then I got lazy in the test and just called `str` on it instead of `Path(str())`. (Pytest gives back a weird type for paths created with its tempdir functionality, which is why turning it into a string was necessary in the first place.)

I guess in the end the annotation for `_load_file` directly depends on whatever `open` accepts?

**Comment by cthoyt** [comment]
I guess in the end the annotation for _load_file directly depends on whatever open accepts?

Yes. Would a magic function `accept_what_this_takes(open, 0)` be nice?

**Comment by scolby33** [comment]
It would be...

Here's how mypy sees `open`:

```python
def open(file: Union[builtins.str, builtins.bytes, builtins.int, builtins._PathLike[Any]], mode: builtins.str =, buffering: builtins.int =, encoding: Union[builtins.str, None] =, errors: Union[builtins.str, None] =, newline: Union[builtins.str, None] =, closefd: builtins.bool =) -> typing.IO[Any]
```
